// ----------------------------------------------------------------------
// Airports raw data

export const airportNames = [
  'John F. Kennedy International Airport',
  'Toronto Pearson International Airport',
  'Benito Juárez International Airport',
  'São Paulo/Guarulhos–Governador André Franco Montoro International Airport',
  'Ministro Pistarini International Airport',
  'Heathrow Airport',
  'Charles de Gaulle Airport',
  'Berlin Brandenburg Airport',
  'Leonardo da Vinci International Airport',
  'Adolfo Suárez Madrid–Barajas Airport',
  'Sydney Kingsford Smith Airport',
  'Auckland Airport',
  'Beijing Capital International Airport',
  'Chhatrapati Shivaji Maharaj International Airport',
  'Narita International Airport',
  'Incheon International Airport',
  'Sheremetyevo International Airport',
  'Cape Town International Airport',
  'Cairo International Airport',
  'Murtala Muhammed International Airport',
  'Jomo Kenyatta International Airport',
  'King Khalid International Airport',
  'Istanbul Airport',
  'Imam Khomeini International Airport',
  'Soekarno–Hatta International Airport',
  'Tan Son Nhat International Airport',
  'Suvarnabhumi Airport',
  'Kuala Lumpur International Airport',
  'Changi Airport',
  'Ninoy Aquino International Airport',
  'Jinnah International Airport',
  'Hazrat Shahjalal International Airport',
  'Dubai International Airport',
  'King Abdulaziz International Airport',
];

export const airportCodes = [
  'JFK',
  'YYZ',
  'MMMX',
  'GRU',
  'EZE',
  'LHR',
  'CDG',
  'BER',
  'FCO',
  'MAD',
  'SYD',
  'AKL',
  'PEK',
  'BOM',
  'NRT',
  'ICN',
  'SVO',
  'CPT',
  'CAI',
  'LOS',
  'NBO',
  'RUH',
  'IST',
  'IKA',
  'CGK',
  'SGN',
  'BKK',
  'KUL',
  'SIN',
  'MNL',
  'KHI',
  'DAC',
  'DXB',
  'JED',
  'MED',
];

export const cityNames = [
  'New York',
  'Toronto',
  'Mexico',
  'São Paulo',
  'Buenos Aires',
  'London',
  'Paris',
  'Berlin',
  'Rome',
  'Madrid',
  'Sydney',
  'Auckland',
  'Beijing',
  'Mumbai',
  'Tokyo',
  'Seoul',
  'Moscow',
  'Cape Town',
  'Cairo',
  'Lagos',
  'Nairobi',
  'Riyadh',
  'Istanbul',
  'Tehran',
  'Jakarta',
  'Ho Chi Minh City',
  'Bangkok',
  'Kuala Lumpur',
  'Singapore',
  'Manila',
  'Karachi',
  'Dhaka',
  'Dubai',
  'Mecca',
];

export const countryNames = [
  'United States',
  'Canada',
  'Mexico',
  'Brazil',
  'Argentina',
  'United Kingdom',
  'France',
  'Germany',
  'Italy',
  'Spain',
  'Australia',
  'New Zealand',
  'China',
  'India',
  'Japan',
  'South Korea',
  'Russia',
  'South Africa',
  'Egypt',
  'Nigeria',
  'Kenya',
  'Saudi Arabia',
  'Turkey',
  'Iran',
  'Indonesia',
  'Vietnam',
  'Thailand',
  'Malaysia',
  'Singapore',
  'Philippines',
  'Pakistan',
  'Bangladesh',
  'United Arab Emirates',
];
export const tripType = [
  'round',
  'oneway',
  'round',
  'round',
  'oneway',
  'round',
  'round',
  'oneway',
  'round',
];
export const totalSeats = [2, 4, 5, 30, 10, 3, 20, 15, 7];
